# https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html#splitting-out-vars
aur_helper: yay

default_roles:
# System
  - nvidia
  - audio
  - fonts
  - shell
  - ly

# Desktop Environment
  - assets
  - niri
  - quickshell
  - gtk_qt
  - wezterm
  - normcap

# Package Managers
  - flatpak

# TUI applications
  - neovim
  - yazi
  - opencode

# GUI applications
  - browsers
  - obs
  # - stremio
  - vscode
