# https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html#splitting-out-vars
aur_helper: yay

default_roles:
# System
  - security
  - snapshots
  - gpu
  - audio
  - fonts
  - shell
  - display_manager

# Desktop Environment
  - desktop_entries
  - assets
  - niri
  - quickshell
  - gtk_qt
  - wezterm
  - normcap

# Package Managers
  - pkg_managers

# TUI applications
  - tmux
  - neovim
  - yazi
  - opencode

# GUI applications
  - browsers
  - obs
  - stremio
  - vscode
  - obsidian

# Services
  - docker
  - searxng
