# https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html#splitting-out-vars
aur_helper: yay

default_roles:
# Package Managers
  - pkg_managers

# System
  - security
  - snapshots
  - gpu
  - audio
  - fonts
  - shell
  - display_manager

# Desktop Environment
  - assets
  - gtk_qt
  - niri
  - quickshell
  # - wezterm
  - alacritty
  - normcap
  - walker

# TUI applications
  - tmux
  - neovim
  - yazi
  - opencode
  - ytdlp

# GUI applications
  - browsers
  - obs
  - stremio
  - vscode
  - obsidian
  - nautilus

# Services
  - docker
  - searxng

# After roles
  - desktop_entries
