---
- name: "{{ ansible_facts['distribution'] }} | Install Niri"
  community.general.pacman:
    name:
      - xdg-desktop-portal-gnome
      - xwayland-satellite
      - niri
      - org.freedesktop.secrets
      - mako
      - fuzzel
      - hyprpaper
      - libsecret
      - gnome-keyring
      - seahorse
      - flameshot # Screenshot tool with annotations
    state: present
  become: true
