---
- name: "{{ role_name | capitalize }} | Checking for {{ ansible_distribution }} Config"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name | capitalize }} | Run {{ ansible_distribution }} Tasks"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "{{ role_name | capitalize }} | Setup Niri Config Symlink"
  ansible.builtin.include_tasks: "../../../tasks/config_symlink.yml"
  vars:
    app_name: "Niri"
    config_dir_name: "niri"
    src_subdir: "niri"

- name: "{{ role_name | capitalize }} | Setup Hyprpaper Config Symlink"
  ansible.builtin.include_tasks: "../../../tasks/config_symlink.yml"
  vars:
    app_name: "Hyprpaper"
    config_dir_name: "hypr"
    src_subdir: "hypr"