---
- name: "Main | Checking for {{ ansible_facts['distribution'] }} Config"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}.yml"
  register: distribution_config

- name: "Main | Run {{ ansible_facts['distribution'] }} Tasks"
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"
  when: distribution_config.stat.exists

- name: "Main | Setup Niri Config Symlink"
  ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/deploy_config.yml"
  vars:
    app_name: Niri
    src_subpath: niri
    dest_path: "{{ ansible_facts['user_dir'] }}/.config/niri"

- name: "Main | Setup Hyprpaper Config Symlink"
  ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/deploy_config.yml"
  vars:
    app_name: Hyprpaper
    src_subpath: hypr
    dest_path: "{{ ansible_facts['user_dir'] }}/.config/hypr"