---
- name: "Checking tasks for {{ ansible_facts['distribution'] }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}.yml"
  register: niri_tasks

- name: "Run tasks for {{ ansible_facts['distribution'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"
  when: niri_tasks.stat.exists

- name: "Deploy config symlink"
  ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/deploy_config.yml"
  vars:
    app_name: Niri
    src_subpath: niri
    dest_path: "{{ ansible_facts['user_dir'] }}/.config/niri"

- name: "Deploy Hyprpaper config symlink"
  ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/deploy_config.yml"
  vars:
    app_name: Hyprpaper
    src_subpath: hypr
    dest_path: "{{ ansible_facts['user_dir'] }}/.config/hypr"
