---
- name: "{{ ansible_facts['distribution'] }} | Install Shell packages"
  community.general.pacman:
    name:
      - zsh
      - fzf
      - fastfetch
      - less
    state: present
  become: true