---
- name: System Automation and Dotfiles Management
  hosts: localhost
  connection: local

  tasks:
    - name: Create 'aur_builder' user
      ansible.builtin.import_tasks: tasks/create_aur_builder.yml
      register: aur_builder_user
      when: ansible_facts['distribution'] == 'Archlinux'
      tags: always

    # Examples:
    # Run all: dotfiles
    # Run specific roles: dotfiles --tags neovim,vscode
    # Skip specific roles: dotfiles --skip-tags nvidia,ly
    - name: Set roles
      ansible.builtin.set_fact:
        role_list: >-
          {{ ansible_run_tags | list if (ansible_run_tags | list != ['all'])
            else (default_roles | difference(ansible_skip_tags) | sort if (ansible_skip_tags)
            else default_roles | sort) }}
      tags: always

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ role_name }}"
        name: "{{ role_name }}"
      loop_control:
        loop_var: role_name
      with_items: "{{ role_list }}"
      tags: always

  post_tasks:
    - name: Delete 'aur_builder' user
      ansible.builtin.import_tasks: tasks/delete_aur_builder.yml
      when: ansible_facts['distribution'] == 'Archlinux'
      tags: always
