---
- name: "{{ ansible_facts['distribution'] }} | Import Sublime Text key"
  ansible.builtin.rpm_key:
    state: present
    key: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
  become: true
  
- name: "{{ ansible_facts['distribution'] }} | Add sublime-text-stable repository"
  ansible.builtin.yum_repository:
    name: sublime-text-stable
    description: Sublime Text repo
    baseurl: 'https://download.sublimetext.com/rpm/stable/x86_64'
    gpgcheck: true
    gpgkey: 'https://download.sublimetext.com/sublimehq-pub.gpg'
  become: true
  
- name: "{{ ansible_facts['distribution'] }} | Install Sublime Text"
  ansible.builtin.dnf5:
    name: sublime-text
    state: present
  become: true

