---
- name: "{{ ansible_facts['distribution'] }} | [AUR] Install Quickshell"
  kewlfft.aur.aur:
    use: "{{ aur_helper }}"
    name:
      - quickshell
      # - noctalia-shell
    state: present
  become: true
  become_user: aur_builder


