---
- name: "{{ role_name | capitalize }} | {{ ansible_distribution }} | [AUR] Install Visual Studio Code"
  kewlfft.aur.aur:
    use: "{{ aur_helper }}"
    name: visual-studio-code-bin
    state: present
  become: true
  become_user: aur_builder
