---
- name: "Checking tasks for {{ ansible_facts['distribution'] }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}.yml"
  register: vscode_tasks

- name: "Run tasks for {{ ansible_facts['distribution'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"
  when: vscode_tasks.stat.exists

- name: "Deploy config symlink"
  ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/deploy_config.yml"
  vars:
    app_name: VSCode
    dest_path: "{{ ansible_facts['user_dir'] }}/.config/code"
