---
- name: "{{ role_name | capitalize }} | {{ ansible_distribution }} | [AUR] Install OpenCode"
  kewlfft.aur.aur:
    use: "{{ aur_helper }}"
    name: opencode-bin
    state: present
  become: true
  become_user: aur_builder
