---
- name: "Checking tasks for {{ ansible_facts['distribution'] }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}.yml"
  register: desktop_entries_tasks

- name: "Run tasks for {{ ansible_facts['distribution'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"
  when: desktop_entries_tasks.stat.exists

# - name: "Deploy config symlink"
#  ansible.builtin.include_tasks: "../../../tasks/config_symlink.yml"
#  vars:
#    app_name: "Neovim"
#    config_dir_name: "nvim"
