---
- name: "{{ role_name | capitalize }} | {{ ansible_distribution }} | [Flatpak] Install NormCap OCR"
  community.general.flatpak:
    name: com.github.dynobo.normcap
    state: present
    method: user
    remote: flathub