---
- name: "{{ ansible_facts['distribution'] }} | Install Firefox"
  community.general.pacman:
    name:
      - firefox
      - torbrowser-launcher
    state: present
  become: true

- name: "{{ ansible_facts['distribution'] }} | [AUR] Install Zen Browser and Brave"
  kewlfft.aur.aur:
    use: "{{ aur_helper }}"
    name:
      - zen-browser-bin
      - brave-bin
      - librewolf-bin
    state: present
  become: true
  become_user: aur_builder