---
- name: "{{ role_name | capitalize }} | {{ ansible_distribution }} | Install Firefox"
  community.general.pacman:
    name:
      - firefox
    state: present
  become: true

- name: "{{ role_name | capitalize }} | {{ ansible_distribution }} | [AUR] Install Zen Browser and Brave"
  kewlfft.aur.aur:
    use: "{{ aur_helper }}"
    name:
      - zen-browser-bin
      - brave-bin
    state: present
  become: true
  become_user: aur_builder