---
# Librewolf - https://repo.librewolf.net/librewolf.repo
- name: "{{ ansible_facts['distribution'] }} | Add Librewolf repository"
  ansible.builtin.yum_repository:
    name: librewolf-repo
    description: LibreWolf Software Repository
    baseurl: 'https://repo.librewolf.net'
    gpgcheck: true
    gpgkey: 'https://repo.librewolf.net/pubkey.gpg'
  become: true

# Brave - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
- name: "{{ ansible_facts['distribution'] }} | Add Brave repository"
  ansible.builtin.yum_repository:
    name: brave-repo
    description: Brave Browser
    baseurl: 'https://brave-browser-rpm-release.s3.brave.com/$basearch'
    gpgcheck: true
    gpgkey: 'https://brave-browser-rpm-release.s3.brave.com/brave-core.asc'
  become: true

- name: "{{ ansible_facts['distribution'] }} | Install Browsers"
  ansible.builtin.dnf5:
    name:
      - torbrowser-launcher
      - librewolf
      - brave-browser
    state: present
  become: true
  
- name: "{{ ansible_facts['distribution'] }} | [Flatpak] Install Zen browser"
  community.general.flatpak:
    name:
      - app.zen_browser.zen
    state: present
    remote: flathub
