---
- name: "Checking tasks for {{ ansible_facts['distribution'] }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}.yml"
  register: app_role_tasks

- name: "Run tasks for {{ ansible_facts['distribution'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"
  when: app_role_tasks.stat.exists

- name: "Deploy config symlink"
  ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/deploy_config.yml"
  vars:
    app_name: tmux
    dest_path: "{{ ansible_facts['user_dir'] }}/.config/tmux"

- name: "Clone tmux plugin manager"
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm.git"
    dest: "{{ ansible_facts['user_dir'] }}/.config/tmux/plugins/tpm"
