---
- name: "{{ role_name | capitalize }} | {{ ansible_distribution }} | [Flatpak] Install Stremio Beta"
  community.general.flatpak:
    name: com.stremio.Stremio
    state: present
    method: user
    remote: flathub-beta