---
- name: "{{ ansible_facts['distribution'] }} | Install Ly"
  community.general.pacman:
    name:
      - ly
      - brightnessctl
    state: present
  become: true

- name: "{{ ansible_facts['distribution'] }} | Enable service"
  ansible.builtin.systemd:
    name: ly.service
    enabled: true
  become: true
