---
- name: "{{ ansible_facts['distribution'] }} | Install Ly"
  community.general.pacman:
    name:
      - ly
      - brightnessctl
    state: present
  become: true

- name: "{{ ansible_facts['distribution'] }} | Enable service"
  ansible.builtin.systemd:
    name: ly@tty2.service
    enabled: true
  become: true

- name: "{{ ansible_facts['distribution'] }} | Disable getty2"
  ansible.builtin.systemd:
    name: getty@tty2.service
    enabled: false
    state: stopped
  become: true
