---
- name: "Checking tasks for {{ ansible_facts['distribution'] }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}.yml"
  register: alacritty_tasks

- name: "Run tasks for {{ ansible_facts['distribution'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"
  when: alacritty_tasks.stat.exists

#- name: "Deploy config symlink"
#  ansible.builtin.include_tasks: "{{ playbook_dir }}/tasks/deploy_config.yml"
#  vars:
#    app_name: Alacritty
#    dest_path: "{{ ansible_facts['user_dir'] }}/.config/alacritty"
