---
- name: "Main | Checking for {{ ansible_facts['distribution'] }} Config"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}.yml"
  register: distribution_config

- name: "Main | Run {{ ansible_facts['distribution'] }} Tasks"
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"
  when: distribution_config.stat.exists