---
- name: "{{ role_name | capitalize }} | {{ ansible_distribution }} | Install Ly"
  community.general.pacman:
    name:
      - ly
      - brightnessctl
    state: present
  become: true

- name: "{{ role_name | capitalize }} | {{ ansible_distribution }} | Enable service"
  ansible.builtin.systemd:
    name: ly.service
    enabled: true
  become: true